# -*- coding: utf-8 -*-
"""Ex7.7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UXWNUaqV50wgAYugZnEcFh1wemVo4K6D
"""

import numpy as np
import matplotlib.pyplot as plt

# Define the S-curve function
def s_curve(x, r, b):
    return 1 - (1 - x**r)**b

# Parameters for r and b
r_values = [2, 5]
b_values = [10, 50]

x = np.linspace(0, 1, 1000)

# Plot S-curves
plt.figure(figsize=(12, 8))

for r in r_values:
    for b in b_values:
        y = s_curve(x, r, b)
        plt.plot(x, y, label=f"r={r}, b={b}")

# Add labels, title, and legend
plt.xlabel("Jaccard similarity (x)")
plt.ylabel("Probability of becoming a candidate pair (y)")
plt.axhline(0.5, color='gray', linestyle='--', linewidth=1, label="y = 0.5")
plt.legend()
plt.grid(True)
plt.show()